### ISSUE TITLE
Missing taxa

### ISSUE THREAD

**Issue by alephreish** [maryamrabiee/INSTRAL#2]
Hi! First first of all, thanks for the quite unique piece of software!

In the README it is stated that the `input trees can have missing taxa` with respect to the backbone species tree. However, with the current code a situation in which some taxa don't appear on _any_ of the gene trees is not tolerated:

```bash
$ # create a bogus set of gene trees from simulated_14taxon.gene.tre w/o tip 3
$ tail -n+2 Instral/test_data/simulated_14taxon.gene.tre | nw_prune - 3 > gene_trees.tre
$
$ # and a bogus species tree w/o tip 2
$ head -n 1 Instral/test_data/simulated_14taxon.gene.tre | nw_prune - 2 > backbone.tre
$ # instral fails
$ instral -f backbone.tre -i gene_trees.tre --placement 2

================== ASTRAL ===================== 

This is ASTRAL version 5.13.5
Gene trees are treated as unrooted
(((9:0.00631373,1:0.00662961):0.01689917,((12:0.02638255,(10:0.0076733,(3:0.00398912,4:0.00225677):0.0078636):1.1454E-4):0.00264884,(8:0.01079647,(5:0.00511083,7:0.00414615):0.00822591):0.01132526):0.00801222):0.09955047,((11:0.01203878,(6:0.01012353,13:0.01137256):5.0196E-4):0.01774429,0:0.04173999):0.14599794);
1 extra trees read from null
Problem using GPU. Proceeding without GPU
There are 64 threads used to run.
9 trees read from gene_trees.tre
Reading trees finished in 0.081 secs
Memory2147MB
Exception in thread "main" java.lang.RuntimeException: Mapping between gene tree and species tree taxon names doesn't seem right. We couldn't find species 3 in gene trees.
	at phylonet.coalescent.SpeciesMapper.getGeneNamesForSpeciesName(SpeciesMapper.java:198)
	at phylonet.coalescent.SpeciesMapper.stToGt(SpeciesMapper.java:207)
	at phylonet.coalescent.CommandLine.readExtraInputTrees2(CommandLine.java:1190)
	at phylonet.coalescent.CommandLine.main(CommandLine.java:740)
```

The problem can be remedied by adding any gene tree that contains all the tips even if it is not informative for placing the query, e.g. the species tree itself:

```bash
$ cat backbone.tre >> gene_trees.tre 
$ instral -f backbone.tre -i gene_trees.tre --placement 2

================== ASTRAL ===================== 

This is ASTRAL version 5.13.5
Gene trees are treated as unrooted
(((9:0.00631373,1:0.00662961):0.01689917,((12:0.02638255,(10:0.0076733,(3:0.00398912,4:0.00225677):0.0078636):1.1454E-4):0.00264884,(8:0.01079647,(5:0.00511083,7:0.00414615):0.00822591):0.01132526):0.00801222):0.09955047,((11:0.01203878,(6:0.01012353,13:0.01137256):5.0196E-4):0.01774429,0:0.04173999):0.14599794);
1 extra trees read from null
Problem using GPU. Proceeding without GPU
There are 64 threads used to run.
**Skipping the following tree(s) because they did not contain new species[10]**
9 trees read from gene_trees.tre
Reading trees finished in 0.082 secs
Memory2147MB
All output trees will be *arbitrarily* rooted at 6

======== Running the main analysis
Number of taxa: 14 (14 species)
Taxa: [6, 13, 0, 5, 10, 11, 4, 7, 2, 1, 8, 12, 9, 3]
Taxon occupancy: {11=9, 12=9, 13=9, 0=9, 1=9, 2=9, 4=9, 5=9, 6=9, 7=9, 8=9, 9=9, 10=9}
...
ASTRAL finished in 1.131 secs
```

Does this workaround influence the inference? I think either way, this should be addressed in more explicitly.

**Comment by alephreish** [comment]
OK, I think the scenario of missing species is not exactly what INSTRAL is designed for. Strictly speaking, it doesn't expect that the gene trees will systematically not have particular species besides the query.
